server:
  port: 8081

gszrpc:
  gushizhao:
    consumer:
      registryAddress: 127.0.0.1:2181
      registryType: zookeeper
      loadBalanceType: zkconsistenthash
      proxy: cglib
      version: 1.0.0
      group: hello
      serializationType: protostuff
      timeout: 30000
      async: false
      oneway: false
      heartbeatInterval: 30000
      scanNotActiveChannelInterval: 60000
      retryInterval: 1000
      retryTimes: 3
      # enableResultCache
      enableResultCache: true
      # resultCacheExpire
      resultCacheExpire: 10000
      # enableDirectServer
      enableDirectServer: true
      # directServerUrl
      directServerUrl: 127.0.0.1:27880
      # enableDelayConnection
      enableDelayConnection: true
      # corePoolSize
      corePoolSize: 16
      # maximumPoolSize
      maximumPoolSize: 16
      # flowType
      flowType: print
      # enableBuffer
      enableBuffer: true
      # bufferSize
      bufferSize: 40960
      # reflectType
      reflectType: cglib
      # fallbackClassName
      fallbackClassName: xxx.xxx.xxx.Xxx
      # enableRateLimiter
      enableRateLimiter: true
      # rateLimiterType
      rateLimiterType: counter
      # permits
      permits: 100
      # milliSeconds
      milliSeconds: 1000
      # rateLimiterFailStrategy, direct/fallback/exception
      rateLimiterFailStrategy: direct
      # enableFusing
      enableFusing: true
      # fusingType: counter/percent
      fusingType: counter
      # totalFailure
      totalFailure: 10
      # fusingMilliSeconds
      fusingMilliSeconds: 5000
      # exceptionPostProcessorType
      exceptionPostProcessorType: print